apiVersion: v1
kind: Secret
metadata:
  name: mage.plural-postgres-mage.credentials.postgresql.acid.zalan.do
  labels:
{{ include "mage-plural.labels" . | indent 4 }}
stringData:
  username: mage
  password: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mage-postgres-dsn
  labels:
{{ include "mage-plural.labels" . | indent 4 }}
stringData:
  dsn: {{ .Values.postgres.dsn }}