{{- if (index .Values "rook-ceph" "monitoring" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  labels:
    team: rook
    {{- include "rook.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: csi-http-metrics
      path: /metrics
      interval: 5s
    # comment csi-grpc-metrics realated information if csi grpc metrics is not enabled
    # - port: csi-grpc-metrics
    #   path: /metrics
    #   interval: 5s
{{- end }}
