apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels: {{- include "tensorboards.labels" . | nindent 4 }}
  name: {{ include "tensorboards.fullname" . }}-web-app
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.global.istioNamespace }}/sa/istio-ingressgateway-service-account
  selector:
    matchLabels:
      {{- include "tensorboards.selectorLabels" . | nindent 6 }}
