apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tensorboards.fullname" . }}-web-app
  labels:
    {{- include "tensorboards.labels" . | nindent 4 }}
spec:
  {{- if not .Values.webApp.autoscaling.enabled }}
  replicas: {{ .Values.webApp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tensorboards.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webApp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tensorboards.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tensorboards.serviceAccountName" . }}-web-app
      securityContext:
        {{- toYaml .Values.webApp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
            - name: website
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: / # TODO: check if this is correct
          #     port: website
          # readinessProbe:
          #   httpGet:
          #     path: / # TODO: check if this is correct
          #     port: website
          resources:
            {{- toYaml .Values.webApp.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "tensorboards.fullname" . }}-web-app-parameters
      {{- with .Values.webApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
