{{- if "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-azure-blob-env-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
type: Opaque
data:
{{- if .Values.artifactRoot.azureBlob.connectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.artifactRoot.azureBlob.connectionString | b64enc }}
{{- end }}
{{- if .Values.artifactRoot.azureBlob.accessKey }}
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.artifactRoot.azureBlob.accessKey | b64enc }}
{{- end }}
{{- end }}
