apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5000
      targetPort: http
      protocol: TCP
      name: mlflow
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
