apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "pipelines.labels" . | nindent 4 }}
  name: kubeflow-pipelines-container-builder
  namespace: kubeflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "pipelines.labels" . | nindent 4 }}
  name: pipeline-runner
  namespace: kubeflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "pipelines.labels" . | nindent 4 }}
  name: kubeflow-pipelines-viewer
  namespace: kubeflow
