apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "mxnet.labels" . | nindent 4 }}
  name: {{ include "mxnet.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mxnet.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mxnet.serviceAccountName" . }}
    namespace: kubeflow
