apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: deploys the zalando postgres operator for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.8.18'
  - type: helm
    name: rook
    repo: rook
    version: '>= 0.1.4'
    optional: true
  - type: helm
    name: minio
    repo: minio
    version: '>= 0.1.4'
    optional: true
  - type: terraform
    name: aws
    repo: postgres
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: azure
    repo: postgres
    version: '>= 0.1.15'
    optional: true
  - type: terraform
    name: equinix
    repo: postgres
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: postgres
    version: '>= 0.1.0'
    optional: true
