airbyte-web:
  stage: push
  only:
  - main
  script:
  - vendor_image airbyte/webapp:0.32.5-alpha airbyte

airbyte-sched:
  stage: push
  only:
  - main
  script:
  - vendor_image airbyte/scheduler:0.32.5-alpha airbyte

airbyte-server:
  stage: push
  only:
  - main
  script:
  - vendor_image airbyte/server:0.32.5-alpha airbyte

airbyte-worker:
  stage: push
  only:
  - main
  script:
  - vendor_image airbyte/worker:0.32.5-alpha airbyte

temporal:
  stage: push
  only:
  - main
  script:
  - vendor_image temporalio/auto-setup:1.7.0 airbyte
  - vendor_image temporalio/auto-setup:1.13.1 airbyte
  - vendor_image bitnami/kubectl:latest airbyte