gitlab-runner:
  stage: push
  only:
  - main
  script:
  - vendor_image gitlab/gitlab-runner:alpine-v14.0.0 gitlab
  - vendor_image gitlab/gitlab-runner:alpine-v14.1.0 gitlab
  - vendor_image gitlab/gitlab-runner:alpine-v14.2.0 gitlab
  - vendor_image gitlab/gitlab-runner:alpine-v14.3.0 gitlab
  - vendor_image gitlab/gitlab-runner:alpine-v14.4.0 gitlab
