apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elasticsearch-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kibana.kubeflow-aws.com
    port:
      name: http
      number: 80
      protocol: HTTP
    # Upgrade HTTP to HTTPS
    tls:
      httpsRedirect: true
  - hosts:
    - kibana.kubeflow-aws.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: elasticsearch-ingressgateway-certs
