apiVersion: v2
name: clickhouse
description: helm chart for clickhouse
type: application
version: 0.1.2
appVersion: 0.21.0
dependencies:
- name: altinity-clickhouse-operator
  version: 0.21.1
  repository: https://raw.githubusercontent.com/Altinity/clickhouse-operator/gh-pages
