altinity-clickhouse-operator:
  operator:
    image:
      repository: dkr.plural.sh/clickhouse/altinity/clickhouse-operator
      tag: 0.21.2
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 2m
      memory: 64Mi

  metrics:
    image:
      repository: dkr.plural.sh/clickhouse/altinity/metrics-exporter
      tag: 0.21.2
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 2m
        memory: 128Mi

  serviceMonitor:
    enabled: true

  dashboards:
    enabled: true
    additionalLabels:
      grafana_dashboard: altinity-clickhouse-operator-dashboards
    annotations:
      k8s-sidecar-target-directory: /tmp/dashboards/ClickHouse Dashboards
