{{- if .Values.configSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: plural-postgres-s3
  labels:
    platform.plural.sh/sync: pg
{{ include "postgres.labels" . | indent 4 }}
  annotations:
    kubed.appscode.com/sync: ""
stringData:
{{ toYaml .Values.configSecret.env | indent 2 }}
{{- end }}
