apiVersion: v1
kind: Secret
metadata:
  name: sentry-system-secret
  labels:
    {{- include "sentry-plural.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.sentry.system.secretKey | quote | b64enc }}
