clusterSecretStore:
  create: true
  provider: {}

external-secrets:
  image:
    repository: dkr.plural.sh/external-secrets/external-secrets/external-secrets
    tag: v0.6.1
    resources: {}
  serviceMonitor:
    enabled: true
  installCRDs: false
  webhook:
    image:
      repository: dkr.plural.sh/external-secrets/external-secrets/external-secrets
      tag: v0.6.1
    resources: {}
    serviceMonitor:
      enabled: true
  certController:
    image:
      repository: dkr.plural.sh/external-secrets/external-secrets/external-secrets
      tag: v0.6.1
    resources: {}
    serviceMonitor:
      enabled: true
