apiVersion: v2
name: mlflow
description: helm chart for mlflow
type: application
version: 0.1.12
appVersion: "v2.3.2"
dependencies:
- name: postgres
  version: 0.2.1
  repository: https://pluralsh.github.io/module-library
- name: oidc-config
  version: 0.1.6
  repository: https://pluralsh.github.io/module-library
  condition: oidc-config.enabled
