apiVersion: v2
name: redis-cluster
description: clustered redis baked and ready for use in plural
type: application
version: 0.1.3
appVersion: "1.16.0"
dependencies:
- name: redis-cluster
  version: 6.2.4
  repository: https://charts.bitnami.com/bitnami
