apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys monitoring crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: helm
    name: rook
    repo: rook
    version: '>= 0.1.3'
    optional: true
  - type: terraform
    name: aws
    repo: monitoring
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: azure
    repo: monitoring
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: equinix
    repo: monitoring
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: monitoring
    version: '>= 0.1.1'
    optional: true
