apiVersion: v1
kind: Secret
metadata:
  name: variables
type: Opaque
data:
{{ if eq .Values.provider "aws" }}
  AWS_REGION: {{ .Region | b64enc | quote }}
  EXP_MACHINE_POOL: {{ .Values.aws.expMachinePool | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
{{end}}
