apiVersion: v2
name: n8n
description: helm chart for n8n
type: application
version: 0.1.0
appVersion: "v1.0.0"

#dependencies:
#- name: postgres
#  version: 0.1.5
#  repository: https://pluralsh.github.io/module-library