apiVersion: v2
name: sentry
description: A Helm chart for deploying sentry on plural
type: application
version: 0.2.16
appVersion: "21.5.1"
dependencies:
- name: sentry
  version: 18.0.0
  repository: https://sentry-kubernetes.github.io/charts
- name: postgres
  version: 0.2.1
  repository: https://pluralsh.github.io/module-library
  condition: postgres.enabled
- name: rabbitmq
  version: 0.1.0
  repository: https://pluralsh.github.io/module-library
- name: clickhouse
  version: 0.1.1
  repository: https://pluralsh.github.io/module-library
  condition: clickhouse.enabled
