postgres:
  version: "15"
  enabled: true
  team: plural
  user: sentry
  dbName: sentry
  ownerChart: sentry

rabbitmq:
  vhostName: sentry
  cluster:
    name: rabbitmq
    namespace: rabbitmq 

configOverlays:
- name: web-cpu
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: web cpu
    documentation: cpu requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'cpu']
- name: web-mem
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: web memory
    documentation: memory requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'memory']
- name: worker-cpu
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: worker cpu
    documentation: cpu requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'cpu']
- name: worker-mem
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: worker memory
    documentation: memory requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'memory']
- name: clickhouse-cpu
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: cpu
  spec:
    name: clickhouse cpu
    documentation: cpu requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'cpu']
- name: clickhouse-mem
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: memory
  spec:
    name: clickhouse memory
    documentation: memory requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'memory']

sentry:
  asHook: false
  images:
    symbolicator:
      repository: dkr.plural.sh/sentry/getsentry/symbolicator
      tag: 23.6.1
    snuba:
      repository: dkr.plural.sh/sentry/getsentry/snuba
      tag: 23.6.1
    sentry:
      repository: dkr.plural.sh/sentry/getsentry/sentry
      tag: 23.6.1-plural3.1.1
    relay:
      repository: dkr.plural.sh/sentry/getsentry/relay
      tag: 23.6.1

  serviceAccount:
    enabled: true
    name: sentry

  externalPostgresql:
    host: plural-postgres-sentry
    port: 5432
    username: sentry
    existingSecret: sentry.plural-postgres-sentry.credentials.postgresql.acid.zalan.do
    existingSecretKey: password
    database: sentry
    sslMode: require

  postgresql:
    enabled: false
  
  kafka:
    enabled: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    image:
      repository: gcr.io/pluralsh/prom/statsd-exporter
      tag: v0.23.1

  redis:
    enabled: false

  rabbitmq:
    enabled: false
    host: rabbitmq.rabbitmq
    vhost: sentry

  nginx:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  sentry:
    billingMetricsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    cron:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    ingestConsumer:
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 300Mi
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    ingestMetricsConsumerPerf:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    ingestMetricsConsumerRh:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    ingestReplayRecordings:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    postProcessForwardErrors:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    postProcessForwardTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    subscriptionConsumerEvents:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    subscriptionConsumerSessions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    subscriptionConsumerTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    web:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 350Mi
    worker:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 750Mi

    existingSecret: sentry-system-secret
    existingSecretKey: key
  relay:
    env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
  snuba:
    consumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    dbInitJob:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@/sentry
  
    migrateJob:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
  
    outcomesConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    replacer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    replaysConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    sessionsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    subscriptionConsumerEvents:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    subscriptionConsumerSessions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    subscriptionConsumerTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    transactionsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    api:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 20m
          memory: 100Mi

    
    
    
    
  symbolicator:
    autoscaling:
      enabled: false
    api:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry


  zookeeper:
    enabled: false

  clickhouse:
    enabled: false
  externalClickhouse:
    host: service-sentry-clickhouse
    tcpPort: 9000
    httpPort: 8123
    username: sentry
    password: ""
    database: sentry
    clusterName: sentry
    singleNode: false

  externalRedis:
    host: redis-master.redis
    password: ""

  externalKafka:
    host: kafka-kafka-bootstrap.kafka

  hooks:
    activeDeadlineSeconds: 600
    dbCheck:
      image:
        repository: gcr.io/pluralsh/library/busybox
        tag: 1.36.0
      env: 
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry
    dbInit:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq:5672/sentry

clickhouse:
  enabled: true
  cluster: sentry
  database: sentry
  user: sentry
  password: change_me

  settings:
    merge_tree/allow_nullable_key: 1
    merge_tree/check_sample_column_is_correct: 0
  
  resources:
    requests:
      cpu: 150m
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 1Gi
  postInstallationHook:
    enabled: true
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
      helm.sh/hook-weight: "4"
    initContainer:
      timeout: "180s"
    image:
      repository: curlimages/curl
      tag: 7.79.1
    command: ["sh", "-c"]
    args:
      - curl -Sv "${CLICKHOUSE_HOST}/?user=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}" -d "SELECT * FROM information_schema.tables where table_schema = '{{ .Values.database }}'" && sleep 10
    envFrom:
      - secretRef:
          name: sentry-snuba-env
    env:
      - name: CLICKHOUSE_HOST
        value: service-sentry-clickhouse.sentry.svc.cluster.local:8123

kafkaTopic: # TODO: hack since the db init fails to create this topic. Remove in the future once it's fixed in snuba.
  enabled: true
  cluster: kafka
  namespace: kafka
