# Default values for sentry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#######################
replicaCount: 1

postgres:
  enabled: true
  team: plural
  user: sentry
  dbName: sentry
  ownerChart: sentry
  infix: ""

rabbitmq:
  vhostName: sentry
  cluster:
    name: rabbitmq
    namespace: rabbitmq 

configOverlays:
- name: web-cpu
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: web cpu
    documentation: cpu requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'cpu']
- name: web-mem
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: web memory
    documentation: memory requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'memory']
- name: worker-cpu
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: worker cpu
    documentation: cpu requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'cpu']
- name: worker-mem
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: worker memory
    documentation: memory requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'memory']
- name: clickhouse-cpu
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: cpu
  spec:
    name: clickhouse cpu
    documentation: cpu requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'cpu']
- name: clickhouse-mem
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: memory
  spec:
    name: clickhouse memory
    documentation: memory requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'memory']

sentry:
  asHook: false # TODO: check if this works for first deployments
  images:
    symbolicator:
      repository: dkr.plural.sh/sentry/getsentry/symbolicator
      tag: 23.5.0
    snuba:
      repository: dkr.plural.sh/sentry/getsentry/snuba
      tag: 23.5.0
    sentry:
      repository: dkr.plural.sh/sentry/getsentry/sentry
      tag: 23.5.0-plural3.0.0
    relay:
      repository: dkr.plural.sh/sentry/getsentry/relay
      tag: 23.5.0

  serviceAccount:
    enabled: true
    name: sentry

  externalPostgresql:
    host: plural-sentry
    port: 5432
    username: sentry
    existingSecret: sentry.plural-sentry.credentials.postgresql.acid.zalan.do
    existingSecretKey: password
    database: sentry
    sslMode: require

  postgresql:
    enabled: false
  
  kafka:
    enabled: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    image:
      repository: gcr.io/pluralsh/prom/statsd-exporter
      tag: v0.23.1

  redis:
    enabled: false

  rabbitmq:
    enabled: false
    host: rabbitmq.rabbitmq
    vhost: sentry

  nginx:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
###################  
  sentry:
    billingMetricsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    cron:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    ingestConsumer:
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 300Mi
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    ingestMetricsConsumerPerf:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    ingestMetricsConsumerRh:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    ingestReplayRecordings:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    postProcessForwardErrors:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    postProcessForwardTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    subscriptionConsumerEvents:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    subscriptionConsumerSessions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    subscriptionConsumerTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    web:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 350Mi
    worker:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 750Mi

    existingSecret: sentry-system-secret
    existingSecretKey: key
  relay:
    env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>


  snuba:
  #################
    consumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    dbInitJob:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
  
    migrateJob:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
  
    outcomesConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    replacer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    replaysConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    sessionsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    subscriptionConsumerEvents:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    subscriptionConsumerSessions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    subscriptionConsumerTransactions:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    transactionsConsumer:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      resources:
        requests:
          cpu: 20m
          memory: 100Mi

  ##################3
    api:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 20m
          memory: 100Mi

    
    
    
    
  symbolicator:
    autoscaling:
      enabled: false
    api:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>


  zookeeper:
    enabled: false

  clickhouse:
    enabled: false
    clickhouse:
      # image: 'gcr.io/pluralsh/yandex/clickhouse-server'
      # imageVersion: '20.8.9.6'
      # init:
      #   image: 'gcr.io/pluralsh/busybox'
      #   imageVersion: latest
      
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  externalClickhouse:
    ## Hostname or ip address of external clickhouse
    ##
    host: service-sentry-clickhouse
    tcpPort: 9000
    httpPort: 8123
    username: admin
    password: change_me
    database: sentry
    clusterName: sentry
    singleNode: false
    # existingSecret: secret-name
    ## set existingSecretKey if key name inside existingSecret is different from 'postgres-password'
    # existingSecretKey: secret-key-name

  externalRedis:
    host: redis-master.redis
    password: ""

  externalKafka:
    host: kafka-kafka-bootstrap.kafka

  hooks:
    activeDeadlineSeconds: 600
    dbCheck:
      image:
        repository: gcr.io/pluralsh/library/busybox
        tag: 1.36.0
      env: 
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>
    dbInit:
      env:
      - name: RABBITMQ_USER
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sentry-rabbitmq-user-credentials
            key: password
      - name: BROKER_URL
        value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@<host>:<port>/<vhost>

clickhouse:
  enabled: true
  cluster: sentry
  database: sentry

  user: admin
  password: change_me
  # -- Whether to use TLS connection connecting to ClickHouse
  secure: false
  # -- Whether to verify TLS certificate on connection to ClickHouse
  verify: false

  resources:
    requests:
      cpu: 150m
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 1Gi
  securityContext:
    enabled: true
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101

  serviceType: ClusterIP
  persistence:
    enabled: true
    size: 20Gi
  backup:
    enabled: false
    
  serviceAccount:
    create: true

  pluralRunbook:
    enabled: true


kafkaTopic: # TODO: hack since the db init fails to create this topic. Remove in the future once it's fixed in snuba.
  enabled: true
  cluster: kafka
  namespace: kafka
