# Default values for sentry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  enabled: true
  team: plural
  user: sentry
  dbName: sentry
  ownerChart: sentry
  infix: ""

rabbitmq:
  vhostName: sentry
  cluster:
    name: rabbitmq
    namespace: rabbitmq 

configOverlays:
- name: web-cpu
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: web cpu
    documentation: cpu requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'cpu']
- name: web-mem
  labels:
    platform.plural.sh/component: sentry-web
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: web memory
    documentation: memory requests for web deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'web', 'resources', 'requests', 'memory']
- name: worker-cpu
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: worker cpu
    documentation: cpu requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'cpu']
- name: worker-mem
  labels:
    platform.plural.sh/component: sentry-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: worker memory
    documentation: memory requests for worker deployment
    updates:
    - path: ['sentry', 'sentry', 'sentry', 'worker', 'resources', 'requests', 'memory']
- name: clickhouse-cpu
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: cpu
  spec:
    name: clickhouse cpu
    documentation: cpu requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'cpu']
- name: clickhouse-mem
  labels:
    platform.plural.sh/component: sentry-clickhouse
    platform.plural.sh/kind: statefulset
    platform.plural.sh/resource: memory
  spec:
    name: clickhouse memory
    documentation: memory requests for clickhouse statefulset
    updates:
    - path: ['sentry', 'sentry', 'clickhouse', 'clickhouse', 'resources', 'requests', 'memory']

sentry:
  asHook: false # TODO: check if this works for first deployments
  images:
    symbolicator:
      repository: gcr.io/pluralsh/getsentry/symbolicator
    snuba:
      repository: gcr.io/pluralsh/getsentry/snuba
    sentry:
      repository: gcr.io/pluralsh/getsentry/sentry
      # tag: 21.5.1-extended
    relay:
      repository: gcr.io/pluralsh/getsentry/relay

  serviceAccount:
    enabled: true
    name: sentry

  externalPostgresql:
    host: plural-sentry
    port: 5432
    username: sentry
    existingSecret: sentry.plural-sentry.credentials.postgresql.acid.zalan.do
    existingSecretKey: password
    database: sentry
    sslMode: require

  postgresql:
    enabled: false
  
  kafka:
    enabled: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    image:
      repository: gcr.io/pluralsh/prom/statsd-exporter
      tag: v0.23.1

  redis:
    enabled: false

  rabbitmq:
    enabled: false
    host: rabbitmq.rabbitmq
    vhost: sentry

  nginx:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  
  sentry:
    existingSecret: sentry-system-secret
    existingSecretKey: key
    web:
      autoscaling:
        enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 350Mi
    worker:
      autoscaling:
        enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 750Mi
    ingestConsumer:
      autoscaling:
        enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 300Mi

  snuba:
    api:
      autoscaling:
        enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    sessionsConsumer:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    consumer:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    outcomesConsumer:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    replacer:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
    transactionsConsumer:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi

  symbolicator:
    autoscaling:
      enabled: true
    api:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi

  zookeeper:
    enabled: false

  clickhouse:
    enabled: false
    clickhouse:
      # image: 'gcr.io/pluralsh/yandex/clickhouse-server'
      # imageVersion: '20.8.9.6'
      # init:
      #   image: 'gcr.io/pluralsh/busybox'
      #   imageVersion: latest
      
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  externalClickhouse:
    ## Hostname or ip address of external clickhouse
    ##
    host: service-sentry-clickhouse
    tcpPort: 9000
    httpPort: 8123
    username: admin
    password: CHAMGE_ME
    database: sentry
    clusterName: sentry
    singleNode: true # TODO: change to false if clickhouse.layout.shardsCount > 1
    # existingSecret: secret-name
    ## set existingSecretKey if key name inside existingSecret is different from 'postgres-password'
    # existingSecretKey: secret-key-name

  externalRedis:
    host: redis-master.redis
    password: ""

  externalKafka:
    host: kafka-kafka-bootstrap.kafka

  hooks:
    activeDeadlineSeconds: 300
    dbCheck:
      image:
        repository: gcr.io/pluralsh/library/busybox
        tag: 1.36.0

clickhouse:
  enabled: true
  cluster: sentry
  database: sentry
