apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "mpi.labels" . | nindent 4 }}
  name: {{ include "mpi.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mpi.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mpi.serviceAccountName" . }}
    namespace: kubeflow
