apiVersion: v1
data:
  kubectl-delivery-image: mpioperator/kubectl-delivery:latest
  lock-namespace: kubeflow
kind: ConfigMap
metadata:
  labels: {{- include "mpi.labels" . | nindent 4 }}
    kustomize.component: mpi-operator
  name: {{ include "mpi.fullname" . }}-config
  namespace: kubeflow
