apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
   {{ include "nocodb.labels" . | nindent 4 }}
  name: nocodb-rules
spec:
  groups:
  - name: nocodb
    rules:
    - alert: NocodbPostgresCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-nocodb-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-nocodb-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: nocodb dbs's cpu has gotten too high
        description: the cpu utilization of your nocodb is higher than recommended
    - alert: NocodbPostgresMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-nocodb-[0-9]+"})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-nocodb-[0-9]+"})
        )  > 1
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: nocodb db's memory has gotten too high
        description: the memory utilization of your nocodb db is higher than recommended
    