apiVersion: v1
kind: Secret
metadata:
  name: nocodb-env
  labels:
{{ include "nocodb.labels" . | indent 4 }}
stringData:
  NC_DB_JSON: {{ toJson .Values.nocodb.dbConfig | quote }}
  NC_AUTH_JWT_SECRET: {{ .Values.nocodb.jwtSecret }}
  {{ if .Values.nocodb.sentryDsn }}
  NC_SENTRY_DSN: {{ .Values.nocodb.sentryDsn }}
  {{ end }}
  {{ if .Values.nocodb.smtp }}
  NC_MAILER: '1'
  NC_MAILER_FROM: {{ .Values.nocodb.smtp.from }}
  NC_MAILER_HOST: {{ .Values.nocodb.smtp.host }}
  NC_MAILER_PORT: {{ .Values.nocodb.smtp.port | quote }}
  NC_MAILER_SECURE: '1'
  NC_MAILER_USER: {{ .Values.nocodb.smtp.user }}
  NC_MAILER_PASS: {{ .Values.nocodb.smtp.password }} 
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: nocodb.plural-nocodb.credentials.postgresql.acid.zalan.do
  labels:
{{ include "nocodb.labels" . | indent 4 }}
stringData:
  username: nocodb
  password: {{ .Values.postgres.password }}