apiVersion: v2
name: minio-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v4.4.27
dependencies:
- name: operator
  version: 4.4.27
  repository: https://operator.min.io/
