apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys redash crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: helm
    name: ingress-nginx
    repo: ingress-nginx
    version: ">= 0.1.2"
  - type: terraform
    name: aws
    repo: redash
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: azure
    repo: redash
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: redash
    version: '>= 0.1.0'
    optional: true