apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-account-percona-xtradb-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: percona-xtradb-cluster-operator
subjects:
  - kind: ServiceAccount
    name: percona-xtradb-cluster-operator
    namespace: {{ .Release.Namespace }}