apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: ghost
spec:
  secretName: ghost-mysql
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi