apiVersion: v1
kind: Secret
metadata:
  name: ghost-mysql
stringData:
  # root password is required to be specified
  ROOT_PASSWORD: {{ .Values.db.rootPassword }}
  # a user name to be created, not required
  USER: {{ .Values.db.username }}
  # a password for user, not required
  PASSWORD: {{ .Values.db.password }}
  # a name for database that will be created, not required
  DATABASE: {{ .Values.db.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghost-env
stringData:
  {{ range $name, $val := .Values.ghost.env }}
  {{ $name }}: {{ $val }}
  {{ end }}
