apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  labels:
{{ include "ghost.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: ghost-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{ if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{ end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: default
      containers:
      - name: ghost
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: ghost-env
        {{- if  .Values.extraEnv }}
        env:
        {{- toYaml .Values.extraEnv | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: ghost
          mountPath: /var/lib/ghost/content
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: ghost
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.volume.size }}
