apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-operator.fullname" . }}
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "knative-operator.selectorLabels" . | nindent 4 }}
