apiVersion: v1
kind: Secret
metadata:
  name: directus.plural-postgres-directus.credentials.postgresql.acid.zalan.do
  labels:
{{ include "directus-plural.labels" . | indent 4 }}
stringData:
  username: directus
  password: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: directus-postgres-dsn
  labels:
{{ include "directus-plural.labels" . | indent 4 }}
stringData:
  dsn: {{ .Values.postgres.dsn }}