apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorflow.fullname" . }}
  namespace: kubeflow
  labels:
    {{- include "tensorflow.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "tensorflow.selectorLabels" . | nindent 4 }}
