apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels: {{- include "profile-controller.labels" . | nindent 4 }}
  name: {{ include "profile-controller.fullname" . }}-kfam
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/{{ .Release.Name }}-central-dashboard
  selector:
    matchLabels:
      {{- include "profile-controller.selectorLabels" . | nindent 6 }}
