apiVersion: v1
{{ with .Values.autoscalerConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 604cb513
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-autoscaler
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.defaultsConfig }}
data:
{{ toYaml . | nindent 2}}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: cdabec96
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-defaults
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.deploymentConfig }}
data:
  {{ toYaml . | nindent 2 }}
{{ end }}
  queueSidecarImage: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:6cd0c234bfbf88ac75df5243c2f9213dcc9def610414c506d418f9388187b771
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: fa67b403
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-deployment
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
{{ with .Values.domainConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
metadata:
  annotations:
    knative.dev/example-checksum: 74c3fc6a
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-domain
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
{{ with .Values.featuresConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
metadata:
  annotations:
    knative.dev/example-checksum: 2cf73688
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-features
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.gcConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: e6149382
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-gc
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.leaderElectionConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 96896b00
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-leader-election
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.loggingConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: d9570453
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-logging
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.networkConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 15954d34
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-network
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.observabilityConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 97c1d10b
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-observability
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.tracingConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 4002b4c2
  labels:
    serving.knative.dev/release: v0.26.0
  name: config-tracing
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
{{ with .Values.istioConfig }}
data:
{{ toYaml . | nindent 2 }}
{{ end }}
kind: ConfigMap
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.26.0
  name: config-istio
  namespace: {{ .Release.Namespace }}
