apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  labels:
    serving.knative.dev/release: "v0.26.0"
    app.kubernetes.io/name: queue-proxy
    app.kubernetes.io/version: "0.26.0"
    app.kubernetes.io/part-of: knative-serving
  name: queue-proxy
  namespace: {{ .Release.Namespace }}
spec:
  image: gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.26.0
