apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: force-strict-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/release: v0.26.0
    networking.knative.dev/ingress-provider: istio
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: webhook
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/release: "v0.26.0"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    matchLabels:
      app: webhook
  portLevelMtls:
    8443:
      mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: domainmapping-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/release: "v0.26.0"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    matchLabels:
      app: domainmapping-webhook
  portLevelMtls:
    8443:
      mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: net-istio-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/release: "v0.26.0"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    matchLabels:
      app: net-istio-webhook
  portLevelMtls:
    8443:
      mode: PERMISSIVE
