apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    serving.knative.dev/release: "v0.26.0"
    app.kubernetes.io/name: activator
    app.kubernetes.io/version: "0.26.0"
    app.kubernetes.io/part-of: knative-serving
  name: activator-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: activator
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    serving.knative.dev/release: "v0.26.0"
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: "0.26.0"
    app.kubernetes.io/part-of: knative-serving
  name: webhook-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: webhook
