apiVersion: v1
kind: Secret
metadata:
  labels:
    serving.knative.dev/release: v0.26.0
  name: domainmapping-webhook-certs
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.26.0
  name: net-istio-webhook-certs
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/release: "v0.26.0"
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: "0.26.0"
    app.kubernetes.io/part-of: knative-serving
