apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "pytorch.labels" . | nindent 4 }}
  name: {{ include "pytorch.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pytorch.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pytorch.serviceAccountName" . }}
    namespace: kubeflow
