apiVersion: v1
kind: Service
metadata:
  name: {{ include "dash-controller.fullname" . }}-controller
  labels:
    {{- include "dash-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dash-controller.selectorLabels" . | nindent 4 }}
