apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: katib-mysql-user
  namespace: kubeflow
spec:
  user: {{ .Values.dbManager.dbUser }}
  clusterRef:
    name: kubeflow-mysql-cluster
    namespace: kubeflow
  password:
    name: {{ .Values.dbManager.config.secret.name }}
    key: PASSWORD
  allowedHosts:
    - "%"
  permissions:
    - schema: {{ .Values.dbManager.config.database.name }}
      tables:
      - "*"
      permissions:
      - ALL
