apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: plural-gitlab
  labels:
    app: postgres
  {{ include "gitlab-plural.labels" . | nindent 4 }}
spec:
  teamId: plural
  volume:
    size: {{ .Values.postgres.storage.size }}
  numberOfInstances: {{ .Values.postgres.replicas }}
  users:
    gitlab:  # database owner
    - superuser
    - createdb
  {{ if .Values.postgres.resources }}
  resources:
  {{ mergeOverwrite .Values.postgres.default.resources .Values.postgres.resources | toYaml | nindent 4 }}
  {{ end }}
  databases:
    gitlabhq_production: gitlab  # dbname: owner
  postgresql:
    version: "13"
  sidecars:
  - image: gcr.io/pluralsh/postgres-exporter:0.8.0
    name: exporter
    ports:
    - containerPort: 9187
      name: http-metrics
      protocol: TCP
    env:
    - name: "DATA_SOURCE_URI"
      value: "127.0.0.1:5432/gitlabhq_production?sslmode=disable"
    - name: "DATA_SOURCE_USER"
      valueFrom:
        secretKeyRef:
          name: postgres.plural-gitlab.credentials.postgresql.acid.zalan.do
          key: username
    - name: "DATA_SOURCE_PASS"
      valueFrom:
        secretKeyRef:
          name: postgres.plural-gitlab.credentials.postgresql.acid.zalan.do
          key: password
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-master
  labels:
    spilo-role: master
    {{ include "gitlab-plural.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-replica
  labels:
    spilo-role: replica
    {{ include "gitlab-plural.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: replica
