apiVersion: v1
kind: Secret
metadata:
  name: objectstore-connection
stringData:
  connection: {{ toYaml .Values.railsConnection | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-connection
stringData:
  config: {{ toYaml .Values.registryConnection | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-pwd
stringData:
  password: {{ .Values.rootPassword }}
{{ if .Values.smtpPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-smtp-password
stringData:
  password: {{ .Values.smtpPassword }}
{{ end }}
{{ if .Values.oidc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: plural-oidc-provider
stringData:
  provider: {{ toYaml .Values.oidc | quote }}
{{ end }}

{{ if .Values.s3secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3credentials
stringData:
{{ range $key, $value := .Values.s3secret }}
  {{ $key }}: {{ $value }}
{{ end }}
{{ end }}