apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: gitlab azure setup
  version: 0.1.2
spec:
  dependencies:
  - name: azure-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'

  providers:
  - azure

  outputs:
    console_msi_client_id: console_msi_client_id
    console_msi_id: console_msi_id
    access_key_id: access_key_id
    secret_access_key: secret_access_key