apiVersion: v1
kind: Service
metadata:
  name: {{ include "volumes.fullname" . }}-controller
  namespace: kubeflow
  labels:
    {{- include "volumes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "volumes.controllerSelectorLabels" . | nindent 4 }}
