apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
  name: {{ include "pipelines.fullname" . }}-web-app
  namespace: kubeflow
spec:
  rules:
    - from:
        - source:
            namespaces:
              - {{ .Values.global.istioNamespace }}
  selector:
    matchLabels:
      {{- include "pipelines.selectorLabels" . | nindent 6 }}
