apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipelines.fullname" . }}-metadata-writer-parameters
  labels: {{- include "pipelines.labels" . | nindent 4 }}
data:
  METADATA_GRPC_SERVICE_SERVICE_HOST: {{ include "pipelines.fullname" . }}-metadata-grpc-server
  METADATA_GRPC_SERVICE_SERVICE_PORT: {{ .Values.metadata.grpc.service.port | quote }}
